### ISSUE TITLE
sqlite3.OperationalError: table sets has no column named keyruneCode

### ISSUE THREAD

**Issue by LeoMosiah** [mtgjson/mtgsqlive#15]
I was trying to compile my AsSets.json file to sqlite but I'm receiving this error:
``Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zion/Projetos/mtgsqlive/mtgsqlive/__main__.py", line 9, in <module>
    main()
  File "/home/zion/Projetos/mtgsqlive/mtgsqlive/json2sql.py", line 39, in main
    parse_and_import_cards(input_file, sql_connection)
  File "/home/zion/Projetos/mtgsqlive/mtgsqlive/json2sql.py", line 209, in parse_and_import_cards
    sql_dict_insert(set_insert_values, "sets", sql_connection)
  File "/home/zion/Projetos/mtgsqlive/mtgsqlive/json2sql.py", line 427, in sql_dict_insert
    cursor.execute(query, data)
sqlite3.OperationalError: table sets has no column named keyruneCode``

and I'm also not finding the pre-compiled SQLite file on the website

**Comment by ZeldaZach** [comment]
Thanks for your report. I recently made changes upstream and didn't mimic them here. I'll work on a fix and have everything good to go soon, including marking the pre-compiled.
