### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by N3OGeorgy** [mtgjson/mtgsqlive#5]
Hello,

I don't have any experience with python.
I took the following steps:

1. Installed python 3.6
2. Used json_to_sql.py file.
3. Used the latest AllSets-x.json from mtgjson website.
4. Used the AllSets-x.db from Initial Release
5. Started the cmd, typed the command and the results are below:

c:\1>python json_to_sql.py 1 c:\1\x.db C:\1\AllSets-x.json
Starting JSON to SQLite Conversion...
Removing old saved database...
Moving old database to 1.old...
Traceback (most recent call last):
  File "json_to_sql.py", line 244, in <module>
    main()
  File "json_to_sql.py", line 217, in main
    las_json_data = json.load(open(as_json_path, 'r'))
  File "C:\Users\***\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\***\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 30: character maps to <undefined>

If i'm using the files from Initial Release ( AllSets_Output.json and json_to_sql.py file from Source code (zip) all is running smoothly.

**Comment by N3OGeorgy** [comment]
Update: 
I have used the last json_to_sql.py file from #4 with a empty .db file created with SQLite and updated python to 3.7, results below:

```
C:\3>python json_to_sql.py 1 C:\3\x3.db C:\3\AllSets-x.json
Starting JSON to SQLite Conversion...
Traceback (most recent call last):
  File "json_to_sql.py", line 357, in <module>
    main()
  File "json_to_sql.py", line 337, in main
    json_data = json.load(open(json_path, 'r'))
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 300, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 355, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 340, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
